name: Todo.ly Pipeline

on:
  push:
    branches:
      - '**'
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '16.0.2'
          distribution: 'adopt'
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Build API Testing framework
        run: ./gradlew clean build
        continue-on-error: true

  CodeInspection:
    runs-on: ubuntu-20.04
    needs: Build
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '16.0.2'
        distribution: 'adopt'
        fetch-depth: 0
    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew
    - name: SonarQube Scan
      run: ./gradlew sonarqube

  AcceptanceTests:
    runs-on: ubuntu-20.04
    needs: CodeInspection
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '16.0.2'
          distribution: 'adopt'
          fetch-depth: 0
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Run Tests
        run: ./gradlew test
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: ${{ github.event.pull_request.merged == true }}
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: "build/test-results/**/*.xml"