name: Todo.ly Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '16.0.2'
          distribution: 'adopt'
      - name: Run tests
        run: |
          chmod +x ./gradlew
          ./gradlew clean test