name: Todo.ly Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  Tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '16.0.2'
          distribution: 'adopt'
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew test

  CodeInspection:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}